apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: poc-multicluster
  namespace: poc-multicluster
spec:
  template:
    spec:
      selector:
        app: nginx
      ports:
      - name: web
        protocol: TCP
        port: 80
        targetPort: 80
  clusters:
  - link: "us-central1-c/poc-multicluster-gke-2"
  - link: "us-central1-c/poc-multicluster-gke-3"
---
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: poc-multicluster
  namespace: poc-multicluster
spec:
  template:
    spec:
      backend:
        serviceName: poc-multicluster
        servicePort: 80
    #   rules:
    #   - host: poc-multicluster.alpha.dev.totvs.app
    #     backend:
    #       serviceName: poc-multicluster
    #       servicePort: 80